#!/usr/bin/env bash
# Writes docs/BUILDER-BUNDLE.md — every handover document in reading order,
# concatenated into one file. Script-written; never edit the bundle by hand.
set -euo pipefail
cd "$(dirname "$0")/.."
OUT=docs/BUILDER-BUNDLE.md
FILES=(
  docs/BUILDER-HANDOVER.md
  docs/local-agents-system-plan.md
  docs/local-agents-builder-brief.md
  docs/pipe-intake-process.md
  docs/local-agents-hardware-note.md
  docs/reference/README-local-seats-original.md
  docs/reference/local-seats-plan-v1.0.md
)
{
  echo "# Builder Bundle — every handover document in one file"
  echo
  echo "Generated by \`docs/make-handover-bundle.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo "Do not edit this file. Edit the sources and re-run the script."
  echo
  for f in "${FILES[@]}"; do
    echo "---"
    echo
    echo "<!-- source: $f -->"
    echo
    cat "$f"
    echo
  done
} > "$OUT"
printf 'wrote %s\nfiles bundled: %s\nlines: %s\n' "$OUT" "${#FILES[@]}" "$(wc -l < "$OUT")"
